#!/usr/bin/env bash
set -euo pipefail

# Production bootstrapper for the OpenStack libvirt stack.
# Runs terraform (init/plan/apply/destroy), ensuring prerequisites exist,
# capturing logs, and surfacing the inventory + SSH artifacts generated by Terraform.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/openstack-libvirt"
LOG_DIR="${REPO_ROOT}/logs"
mkdir -p "${LOG_DIR}"
LOG_FILE="${LOG_DIR}/bootstrap-openstack-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "${LOG_FILE}")
exec 2>&1

ACTION="apply"
VAR_FILE="${TF_VAR_FILE:-terraform.tfvars}"
WORKSPACE="${TF_WORKSPACE:-}"
UPGRADE=false
PARALLELISM=""

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Bootstraps the OpenStack Libvirt Terraform stack (including OpenStack-Ansible configuration).

Options:
  -a, --action <plan|apply|destroy>   Terraform action to run (default: apply)
  -f, --var-file <path>               tfvars file relative to the stack dir or absolute path (default: terraform.tfvars)
  -w, --workspace <name>              Terraform workspace name (creates it if missing)
      --parallelism <n>               Override Terraform parallelism
      --upgrade                       Run 'terraform init -upgrade'
  -h, --help                          Show this usage text

Environment overrides:
  TF_VAR_FILE        Alternate tfvars file (same as --var-file)
  TF_WORKSPACE       Workspace name (same as --workspace)
  TF_PARALLELISM     Parallelism value (same as --parallelism)

All stdout/stderr is tee'd to ${LOG_FILE}.
EOF
}

log() {
  local level="$1"; shift
  printf "%s [%s] %s\n" "$(date +'%Y-%m-%d %H:%M:%S')" "$level" "$*"
}

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || {
    log "ERROR" "Required command '${cmd}' not found. Run scripts/init.sh first."
    exit 1
  }
}

select_workspace() {
  local ws="$1"
  [[ -z "$ws" ]] && return 0
  if terraform workspace list | grep -q "^[[:space:]]*${ws}\$"; then
    terraform workspace select "$ws" >/dev/null
  else
    log "INFO" "Creating Terraform workspace '${ws}'"
    terraform workspace new "$ws" >/dev/null
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -a|--action)
        ACTION="$2"; shift 2;;
      -f|--var-file)
        VAR_FILE="$2"; shift 2;;
      -w|--workspace)
        WORKSPACE="$2"; shift 2;;
      --parallelism)
        PARALLELISM="$2"; shift 2;;
      --upgrade)
        UPGRADE=true; shift;;
      -h|--help)
        usage; exit 0;;
      *)
        log "ERROR" "Unknown argument: $1"
        usage
        exit 1;;
    esac
  done
  [[ -n "${TF_PARALLELISM:-}" && -z "$PARALLELISM" ]] && PARALLELISM="$TF_PARALLELISM"
}

ensure_tfvars() {
  local candidate="$1"
  if [[ -f "$candidate" ]]; then
    printf "%s" "$candidate"
    return
  fi
  if [[ -f "${TF_DIR}/${candidate}" ]]; then
    printf "%s" "${TF_DIR}/${candidate}"
    return
  fi
  log "ERROR" "Cannot locate tfvars file: ${candidate}"
  exit 1
}

run_terraform() {
  log "INFO" "terraform $*"
  terraform "$@"
}

terraform_apply() {
  local plan_path="$1"
  run_terraform plan -input=false -out "$plan_path" -var-file "$VAR_PATH" ${PARALLELISM:+-parallelism="$PARALLELISM"}
  run_terraform apply -input=false "$plan_path"
  rm -f "$plan_path"
}

terraform_destroy() {
  run_terraform destroy -input=false -auto-approve -var-file "$VAR_PATH" ${PARALLELISM:+-parallelism="$PARALLELISM"}
}

summarize_outputs() {
  log "INFO" "Terraform outputs (truncated for key values):"
  terraform output -json | jq '{inventory: .ansible_inventory_file.value, ssh_key: .ssh_private_key_path.value, controllers: .controller_nodes.value}'
}

main() {
  parse_args "$@"

  require_cmd terraform
  require_cmd ansible-playbook
  require_cmd jq

  [[ -d "$TF_DIR" ]] || { log "ERROR" "Terraform directory not found: ${TF_DIR}"; exit 1; }

  VAR_PATH="$(ensure_tfvars "$VAR_FILE")"
  log "INFO" "Using tfvars file: ${VAR_PATH}"

  log "INFO" "Logs captured at ${LOG_FILE}"

  pushd "$TF_DIR" >/dev/null

  trap 'log "ERROR" "Bootstrap interrupted"; exit 1' INT TERM

  local init_args=(-input=false)
  $UPGRADE && init_args+=(-upgrade)
  log "INFO" "Running terraform init"
  run_terraform init "${init_args[@]}"

  select_workspace "$WORKSPACE"

  case "$ACTION" in
    plan)
      run_terraform plan -input=false -var-file "$VAR_PATH" ${PARALLELISM:+-parallelism="$PARALLELISM"}
      ;;
    apply)
      PLAN_FILE="${TF_DIR}/.openstack.tfplan"
      terraform_apply "$PLAN_FILE"
      summarize_outputs
      ;;
    destroy)
      terraform_destroy
      ;;
    *)
      log "ERROR" "Unsupported action: ${ACTION}"
      usage
      exit 1;;
  esac

  popd >/dev/null
  log "INFO" "Completed '${ACTION}' for OpenStack stack."
}

main "$@"
